### ISSUE TITLE
Subscription creation fails with non-latin characters

### ISSUE THREAD

**Issue by jaanttil** [umayr/recurly-js#10]
I'm not sure if I'm misusing the module or if this is a bug in module itself, but I recently noticed that calling recurly.subscriptions.create fails when JSON input has non-latin characters.  For example calling subscription create with (Notice umlauts & and accents):

```
var testData = {
 	plan_code: 'testplan',
  	currency: 'USD',
  	quantity: 1,
  	account: {
     	account_code: '123456',
     	email: 'verena@example.com',
     	first_name: 'Verena',
     	last_name: 'Examplé Ö',
     	billing_info: {
     		number: '4111-1111-1111-1111' ,
     		month: 1,
     		year: 2020
     	}
	}
}
```

Failed with HTTP 400 error: 

`<?xml version="1.0" encoding="UTF-8"?>\n<bad-request>\n  <error line="17" position="434">An error occurred parsing your XML request.</error>\n</bad-request>`

Changing https://github.com/umayr/recurly-js/blob/master/lib/client.js#L25

`'Content-Length': (data) ? data.length : 0, `

to 

`'Content-Length': (data) ? Buffer.byteLength(data, 'utf8') : 0,`

Fixed the issue for me.

**Comment by umayr** [comment]
Definitely an encoding issue. Can you send a pull request?
