### ISSUE TITLE
Retrieve invoice PDF not working for me

### ISSUE THREAD

**Issue by LauraZodrow** [umayr/recurly-js#14]
I am trying to get a recurly invoice pdf. 

```javascript
routes.get('/invoices/:invoice_number', (req, res) => {
  const invoiceNumber = req.params.invoice_number
  recurly.invoices.exportPdf(invoiceNumber, (response) => {
    if(response.status === 'ok') {
      sendPdf(res, response.data)
    } else {
      res.send(response)
    }
  });
});
```
```javascript
const sendPDF = (res, data) => {
  res.setHeader('Content-Type', 'application/pdf');
  res.send(data);
}
```
The recurly response looks like this...
<img width="740" alt="screen shot 2017-01-29 at 2 22 41 pm" src="https://cloud.githubusercontent.com/assets/8607970/22407993/708a1e1c-e62e-11e6-89db-8ff681667167.png">

Client code looks like this...

```javascript
 client.get('/invoices/' + this.props.invoiceNumb)
    .then(function(result) {
      const blob = result.blob()
      var blobUrl = URL.createObjectURL(blob);
      window.open(blobUrl);
    })
    .catch((err) => {
      console.log('invoice error:', err)
    })
```

I've tried adding encoding:null in the request headers and converting the recurly response to a base64 string and a few other things, but whenever the pdf opens in a new url I get "Failed to load PDF document". Any ideas what the problem is?

**Comment by thgreasi** [comment]
Fixed by #15 & released as v2.4.2, closing.
This is how I got it to work:
```js
recurly.invoices.exportPdf(invoiceNumber)
.then(result => {
	res.setHeader('content-type', 'application/pdf');
	# to omit the (automatically added) charset from the content-type header
	res.send(200, new Buffer(result.data));
});
```
