### ISSUE TITLE
List account's coupon redemptions

### ISSUE THREAD

**Issue by kudrykv** [umayr/recurly-js#5]
Seems that the route is missing:
https://dev.recurly.com/docs/lookup-a-coupon-redemption-on-an-account

There is [the route](https://github.com/umayr/recurly-js/blob/master/lib/routes/v2.js#L35) to get last redeemed coupon, but no for the list (no plural `redemptions` route).

**Comment by umayr** [comment]
Closed by #6

**Comment by kudrykv** [comment]
@umayr can you please publish it to the npm?

**Comment by umayr** [comment]
Published. Tag [`v2.4.0`](https://github.com/umayr/recurly-js/releases/tag/v2.4.0)
