### ISSUE TITLE
Create Purchase: Element 'adjustments': This element is not expected."

### ISSUE THREAD

**Issue by kunukmak** [umayr/recurly-js#50]
Whenever I try to use the create purchase endpoint, I get the following error:

> error: {
> node-app_1  |       symbol: 'invalid_xml',
> node-app_1  |       description: 'The provided XML was invalid.',
> node-app_1  |       details: "12:0: ERROR: Element 'adjustments': This element is not expected."
> node-app_1  |     }

My code is as follows:

```javascript
const Recurly = require('recurly-js/promise');

const config = require('./config');

const recurly = new Recurly(config);

/*
  productsAndAmounts is an Array of Object
  schema: {
    productCode: String,
    quantity: Number,
    price: Number
  }
*/
module.exports = async (email, productsAndAmounts, currency = 'CAD') => {
  try {
    const adjustments = productsAndAmounts.map(i => {
      return {
        adjustment: {
          product_code: i.productCode,
          quantity: i.quantity,
          revenue_schedule_type: 'at_invoice',
          unit_amount_in_cents: i.price
        }
      };
    });
    return new Promise((resolve, reject) => {
      recurly.purchases.create(
        {
          account: {
            account_code: email
          },
          currency,
          adjustments
        },
        (err, data) => {
          if (err) {
            reject(err);
          } else {
            resolve(data);
          }
        }
      );
    });
  } catch (e) {
    throw new Error('Error during the purchase attempt');
  }
};
```

I do believe that either something is going on behind the scenes that I fail to understand or there is an issue with the library. Although, I don't completely drop the generic brainfart on my side explanation as well. Could someone please either confirm or debunk my suspicions? Thank you in advance.

**Comment by thgreasi** [comment]
Hey. Can you try spcifying a recent `API_VERSION` in your recurly config options?
This might end up being caused by how the JSON<->XML (de)-serialization library works.
The following:
```js
{
	account,
	currency,
	adjustments: {
		adjustment: productsAndAmounts.map(i => {
			return {
				adjustment: {
					product_code: i.productCode,
					quantity: i.quantity,
					revenue_schedule_type: 'at_invoice',
					unit_amount_in_cents: i.price
				}
			};
		});
	},
}
```

**Comment by kunukmak** [comment]
@thgreasi Thank you for the response.
My settings are as follows (api key and subdomain were changed for security and privacy reasons respectively):

> # Recurly settings
> RECURLY_API_KEY=some_private_api_key
> RECURLY_SUBDOMAIN=some_subdomain
> RECURLY_ENVIRONMENT=sandbox
> RECURLY_DEBUG=false
> RECURLY_API_VERSION=2.21


Config file looks like this:

```
module.exports = {
  API_KEY: process.env.RECURLY_API_KEY,
  SUBDOMAIN: process.env.RECURLY_SUBDOMAIN,
  ENVIRONMENT: process.env.RECURLY_ENVIRONMENT,
  DEBUG: process.env.RECURLY_DEBUG !== 'false',
  API_VERSION: process.env.RECURLY_API_VERSION
};
```

**Comment by kunukmak** [comment]
@thgreasi Yeah, I tried your solution and it worked, I guess I misunderstood how JS to xml translation works. I am extremely grateful, after all my problem is not an issue with a library. Thank you!

**Comment by thgreasi** [comment]
Happy it worked for you @kunukmak
